# Generated by Django 4.1.3 on 2022-12-09 10:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Automatically generated unique ID. Do not change.', primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(null=True)),
                ('delivery', models.BooleanField(blank=True, null=True)),
                ('chauffer_driven', models.BooleanField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('p', 'Pending'), ('i', 'In Progress'), ('c', 'Complete')], default='i', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('sm', 'Saloon/Estate'), ('md', 'Medium 4x4'), ('lg', 'Large 4x4'), ('sf', 'Safari'), ('pu', 'Pickup'), ('xl', 'Bus/Van')], default='sm', max_length=2)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, help_text='Current insurance provider', max_length=100, verbose_name='Insurance Provider')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('coverage', models.CharField(blank=True, choices=[('c', 'Comprehensive'), ('t', 'Third Party'), ('n', 'None')], default='c', help_text='Insurance coverage type', max_length=1)),
            ],
            options={
                'verbose_name': 'insurance provider',
                'verbose_name_plural': 'insurance providers',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('due', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'Pending'), ('c', 'Cleared'), ('e', 'Expired'), ('s', 'Success')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.booking')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='model')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('year', models.IntegerField(default=2022, null=True, validators=[django.core.validators.MaxValueValidator(2023)])),
                ('engine_size', models.IntegerField(default=2500, help_text='Engine size in cc (e.g. 2500, 1600)')),
                ('license_plate', models.CharField(default='KBD 001A', max_length=8)),
                ('color', models.CharField(blank=True, default='White', max_length=50, null=True)),
                ('seats', models.CharField(blank=True, choices=[('5', 'Five'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('8', 'Eight'), ('25', 'Twenty-Five')], max_length=2)),
                ('fuel', models.CharField(blank=True, choices=[('p', 'Petrol'), ('d', 'Diesel')], default='p', max_length=1)),
                ('drivetrain', models.CharField(blank=True, choices=[('AWD', 'All Wheel Drive'), ('FWD', 'Front Wheel Drive'), ('RWD', 'Rear Wheel Drive')], default='RWD', max_length=4)),
                ('transmission', models.CharField(blank=True, choices=[('AT', 'Automatic'), ('MT', 'Manual')], default='AT', max_length=4)),
                ('status', models.CharField(choices=[('a', 'Available'), ('r', 'Reserved'), ('h', 'On Hire'), ('m', 'Maintenance')], default='a', max_length=1)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Automatically generated unique ID. Do not change.', primary_key=True, serialize=False)),
                ('mileage', models.IntegerField(null=True)),
                ('daily_rate', models.IntegerField(default=3500, help_text='Daily rate in Kenyan Shillings')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.category')),
                ('insurance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='rental.insurance')),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.manufacturer')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.carmodel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [],
                'permissions': (('can_change_availability', 'Set car as rented'),),
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
