# Generated by Django 4.1.3 on 2022-12-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='car',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
